export const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
export const pct=v=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});
export const num=v=>Number(v).toLocaleString('ru-RU');
export const dateText=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)?v.split('-').reverse().join('.'):v;
export const codeText=c=>/^\d{10}$/.test(c)?`${c.slice(0,4)} ${c.slice(4,6)} ${c.slice(6,9)} ${c.slice(9)}`:esc(c);
export const fieldLabels={description:'Описание',material:'Материал',purpose:'Назначение',construction:'Конструкция',specifications:'Параметры'};
export function resultHTML(r){
  let html='';
  if(r.groups.length)html+='<div class="group-list" aria-label="Доли товарных групп">'+r.groups.slice(0,8).map(g=>`<span class="group-chip" title="${esc(g.name)}">Группа ${esc(g.code)}<b>${pct(g.share)}%</b></span>`).join('')+'</div>';
  if(r.groups.length>8)html+=`<p class="result-note">Остальные группы: ${pct(r.groups.slice(8).reduce((s,g)=>s+g.share,0))}%. Полный список — в экспорте.</p>`;
  if(r.exact_codes.length>1)html+='<div class="alert-box">В исходных каталогах этому названию соответствуют разные коды. Уточните характеристики перед выбором.</div>';
  if(r.issues.length)html+=`<details class="alert-box"><summary>В ${num(r.issues.length)} исходных строках код отсутствует или некорректен</summary>${r.issues.slice(0,20).map(i=>`<p>${esc(i.file)} · строка ${esc(i.row_number)}: ${esc(i.reason)}. ${esc(i.raw_code)}</p>`).join('')}</details>`;
  if(r.candidates.length){
    html+='<div class="candidate-list">'+r.candidates.map((c,i)=>`<button class="candidate" data-candidate="${i}" aria-label="Код ${esc(c.code)}, открыть основания"><span class="candidate-top"><span class="code">${codeText(c.code)}</span>${c.share===null?'<span>↗</span>':`<span class="percent">${pct(c.share)}<small>%</small></span>`}</span><span class="candidate-name">${esc(c.name)}</span><span class="candidate-meta"><span class="tag">${c.hits[0]?.match==='exact'?'Точное название':c.hits.length?'Пример из каталога':'Номенклатура'}</span><span>${c.contradictions.length?'Есть противоречие':esc(c.hits[0]?.refs[0]?.[0]||'ФНС / дерево CSV')} ↗</span></span>${c.share===null?'':`<span class="candidate-bar" style="width:${Math.min(100,Math.max(0,Number(c.share)||0))}%"></span>`}</button>`).join('')+'</div>';
    if(r.mode!=='code')html+=`<p class="result-note">Доли среди найденных вариантов, не вероятность правильной классификации.${r.other_share?` За пределами списка: ${pct(r.other_share)}%.`:''}</p>`;
  }else html+='<div class="empty-state"><h3>Нужно чуть больше информации</h3><p>Уточните название самого изделия, материал и назначение.<br>Можно также ввести код или его первые цифры.</p></div>';
  if(r.unavailable.length)html+=`<details class="alert-box"><summary>${num(r.unavailable.length)} кодов требуют проверки наличия в номенклатуре</summary>${r.unavailable.slice(0,50).map(c=>`<p><b>${esc(c.code)}</b> — ${esc(c.name)}<br>${esc(c.reason)}</p>`).join('')}${r.unavailable.length>50?'<p>Полный список включён в экспорт.</p>':''}</details>`;
  if(r.questions.length)html+=`<details class="result-note"><summary>Что уточнить для выбора кода</summary><ul>${[...new Set(r.questions)].map(q=>`<li>${esc(q)}</li>`).join('')}</ul></details>`;
  return html+'<div class="result-actions"><button class="secondary-button" id="save-report">Сохранить проверку</button><button class="secondary-button" id="export-report">Экспорт JSON ↓</button><button class="secondary-button" id="export-text">Экспорт TXT ↓</button></div>';
}
export function detailHTML(c){
  return `<h2 class="detail-code" id="detail-title">${codeText(c.code)}</h2><p class="detail-subtitle">${esc(c.name)}</p><div class="result-actions"><button id="copy-code" class="secondary-button">Копировать код</button>${c.share!==null?`<span class="group-chip">Доля соответствия <b>${pct(c.share)}%</b></span>`:''}</div>
  ${c.contradictions.length?`<div class="alert-box">${c.contradictions.map(esc).join('<br>')}</div>`:''}
  <section class="detail-section"><h3>Путь в номенклатуре</h3>${c.path.map(n=>`<div class="tree-row"><code>${esc(n.code)}</code><p>${esc(n.description)}${n.variants.length>1?'<br><strong>В CSV есть разные описания этого узла.</strong>':''}</p></div>`).join('')||'<p class="reference">Промежуточные строки CSV отсутствуют.</p>'}<p class="footnote">Показаны доступные уровни CSV. Пропущенные названия не восстанавливаются автоматически.</p></section>
  ${Object.keys(c.fields).length?`<section class="detail-section"><h3>Сопоставление признаков</h3>${Object.entries(c.fields).map(([key,f])=>`<div class="field-evidence"><strong>${fieldLabels[key]||esc(key)}</strong><span>${Math.round(f.coverage*100)}% основ совпало${f.missing.length?'<br>Не найдены: '+esc(f.missing.join(', ')):''}</span></div>`).join('')}</section>`:''}
  <section class="detail-section"><h3>Исходные соответствия</h3>${c.hits.length?c.hits.map(h=>`<div class="reference"><b>${esc(h.name)}</b><br>${h.match==='exact'?'Точное совпадение названия':'Похожее название'} · ${num(h.reference_count)} исходных строк<br>${h.refs.map(ref=>`${esc(ref[0])} · ${ref[3]?'страница '+esc(ref[3]):'лист «'+esc(ref[1])+'», строка '+esc(ref[2])}`).join('<br>')}</div>`).join(''):'<p class="reference">Вариант найден по номенклатуре, без примера из каталога.</p>'}<p class="reference">ФНС · исходная строка ${esc(c.line)}<br>Период записи: ${dateText(c.start)} — ${c.end?dateText(c.end):'окончание не указано'}</p><a class="secondary-button" href="https://eec.eaeunion.org/comission/department/catr/ett/" target="_blank" rel="noopener noreferrer">Сверить с ЕЭК ↗</a></section>
  <section class="detail-section"><h3>Нормативные совпадения</h3><p class="reference">${esc(c.requirements.note)}</p>${c.requirements.matches.map(m=>`<details class="reference"><summary>${esc(m.source)} · ${esc(m.expression)}</summary><p>${esc(m.record.name||m.record.description_lines?.join(' ')||'')}</p><p>${esc(m.record.requirements||'')}</p></details>`).join('')||'<p class="reference">Кодовые совпадения не найдены. Применимость требований не установлена.</p>'}</section>
  <section class="detail-section"><details><summary>Примечания раздела и группы из среза ФНС</summary><p class="reference">${esc(c.notes.section||'Нет текста')}</p><p class="reference">${esc(c.notes.chapter||'Нет текста')}</p></details></section>
  <div class="alert-box">Код автоматически не подтверждён. Проверьте актуальную редакцию, примечания, ОПИ и техническую документацию товара.</div>`;
}
export function sourcesHTML(m){return `<article class="info-card"><h2>Номенклатура</h2><p><strong>ФНС · срез ${dateText(m.snapshot_date)}</strong><br>${num(m.code_count)} кодов с периодами действия из исходника. Веб-версия поддерживает даты с ${dateText(m.minimum_date)}.</p><p>Дерево CSV: classifikators.ru. Это дополнительный источник названий; дата редакции и полнота не подтверждены.</p><a href="https://eec.eaeunion.org/comission/department/catr/ett/" target="_blank" rel="noopener noreferrer">Официальная номенклатура ЕЭК ↗</a></article>
  <article class="info-card"><h2>Примеры товаров</h2><p>${num(m.pair_count)} уникальных пар «товар — код» из восьми Excel-каталогов и информационного письма. Повторы не усиливают оценку.</p><div class="method-list">${m.sources.map(s=>`<span>${esc(s)}</span>`).join('')}</div><p>Примеры не прошли независимую правовую проверку. Выводы отказного письма не переносятся на другой товар автоматически.</p></article>
  <article class="info-card"><h2>Как считаются проценты</h2><p>Описание: вес 60%, материал: 16%, назначение: 12%, конструкция и параметры: по 6%. Учитываются только заполненные поля; сравниваются поисковые основы слов.</p><p>Вес ветви — квадрат наибольшей оценки её кандидата. Доля последовательно распределяется по префиксам 2 → 4 → 6 → 8 → 10. Повторы не повышают вес.</p><p><strong>Это доли среди найденных вариантов, не откалиброванные вероятности.</strong> 100% может означать, что найден только один вариант. Ненайденная ветвь не получает долю.</p><p class="footnote">Веб-модель проверяет все загруженные совпадения без предварительного ограничения SQLite FTS. Выдача может отличаться от настольной версии 1.2.</p></article>
  <article class="info-card"><h2>Что нужно проверить</h2><ul><li>Действующую редакцию ЕЭК на дату операции.</li><li>Полную цепочку, примечания, ОПИ и классификационные решения.</li><li>Техническую документацию и признаки товара.</li><li>Применимость разрешительных требований отдельно от выбора кода.</li></ul><p>Нет автоматического мониторинга законодательства. Пошлины, льготы, маркировка, запреты и все режимы ввоза не определяются.</p></article>
  <article class="info-card"><h2>Обработка и история</h2><p>Поиск выполняется на вашем устройстве. Описания не отправляются на сервер. Проверки сохраняются только по вашей команде в этом браузере; для переноса используйте экспорт JSON или TXT.</p><p>Сайт и поисковый индекс опубликованы открыто на GitHub Pages. Исходные Excel/PDF и локальная история настольной программы не включены в публикацию.</p></article>
  <article class="info-card"><h2>Версия и воспроизводимость</h2><p>Модель ${esc(m.method)}. Индекс проверяется по SHA-256 перед запуском. Это проверка случайного повреждения, а не защита от изменения сайта владельцем.</p><p class="footnote">Индекс подготовлен ${esc(new Date(m.built_at).toLocaleDateString('ru-RU'))}. Дата подготовки не равна дате обновления законодательства.</p><a href="./public/manifest.json" target="_blank" rel="noopener">Метаданные индекса ↗</a></article>`;}
export function reportText(r){return ['КОНТУР · ТН ВЭД','Подтверждённый код: не установлен',...Object.entries(r.profile).map(([k,v])=>k+': '+v),'',...r.warnings,'','ГРУППЫ',...r.groups.map(g=>`${g.code}: ${pct(g.share)}% — ${g.name}`),'',...r.candidates.flatMap(c=>[`${c.code} — ${c.name}`,c.share===null?'Справочная запись':`Доля соответствия: ${pct(c.share)}%`,...c.path.map(n=>`${n.code}: ${n.description}`),...c.contradictions,...c.hits.flatMap(h=>[h.name,...h.refs.map(ref=>ref.join(' · '))]),c.requirements.note,'']),'Доля скрытых кодов: '+(r.other_share??'не применяется'),'УТОЧНЕНИЯ',...r.questions,'КОДЫ ВНЕ СРЕЗА',...r.unavailable.map(c=>`${c.code} — ${c.name}. ${c.reason}`),'','Версия модели: '+r.version,'SHA-256 индекса: '+r.index_sha256].join('\n');}
